### ISSUE TITLE
C# 7 Support patterns in a switch

### ISSUE THREAD

**Issue by MNF** [asgerhallas/ShinySwitch#3]
Is your class stil useful?

 With C# 7, which shipped with Visual Studio 2017 (Release 15.*), you are able to use Types in case statements - see https://stackoverflow.com/questions/298976/is-there-a-better-alternative-than-this-to-switch-on-type/299001#299001

**Comment by asgerhallas** [comment]
Yes, I actually still use it, primarily because:

1. The syntax is terser. I don't need to write break; all the time :)
2. It can be used as an expression like:

```
    var x = Switch.On(abc)
         .Match<Rectangle>(_ => 1)
         .Match<Circle>(_ => 2)
         .OrThrow();
```

3. It can be sent into other functions and extended.
4. It handles arguments of type `System.Type` so I can use it with reflection like:

```
    var propertyInfo = typeof(X).GetProperty(...)
    Switch.On(propertyInfo.propertyType)
        .Match<string>(DoThis)
        .Match<int>(DoThat)
        .Else(DoNothing);
```

I think there'll come a day where this small lib is not useful any more. But I don't think we are quite there yet :)
